### ISSUE TITLE
Unable to install extension due to v0.5 being present

### ISSUE THREAD

**Issue by simondel** [Augurk/vsts-extension#8]
I'm unable to install this extension because v0.5.0 is already installed in my Azure DevOps organization:
![image](https://user-images.githubusercontent.com/4221997/56126997-81d03480-5f7c-11e9-8903-a6d273f73d58.png)

However, my organization does not allow me to uninstall v0.5.0 because it can't find it. (It's an organization that was ported from TFS in the past).

How can I fix this? Or could you use a different task id? (or make 0.5.0 available somehow)

**Comment by jmezach** [comment]
Hmm, what's interesting here is the extension that uploaded the task (augurk-build-task). I don't believe we ever shipped an extension that used that ID, so I'm not sure how you got it. Perhaps someone manually created an extension with that name at some point and used it to upload the task. I don't think there's much we can do about this from our end though.

I do believe there is a REST API that can be used to manually delete the task. Not sure if it's documented  somewhere, but I believe doing a DELETE call on /_apis/distributedTasks/tasks/<id> would do the trick.

**Comment by simondel** [comment]
Thanks for the info! The API was unable to find the extension. However, sending a `DELETE` to https://extmgmt.dev.azure.com/{org}/_apis/extensionmanagement/installedextensionsbyname/Augurk/augurk?api-version=5.0-preview.1 fixed it 🎉

**Comment by jmezach** [comment]
Good to hear that this was quickly resolved. Enjoy the new version :).
